# Generated by Django 4.1.1 on 2023-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemporaryShp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "shp_file_path",
                    models.CharField(max_length=200, verbose_name="Archivos Shp"),
                ),
                ("layer_crs", models.CharField(max_length=10, verbose_name="EPSG")),
                (
                    "layer_type",
                    models.CharField(
                        choices=[("point", "Puntos"), ("line", "Lineas")],
                        max_length=10,
                        verbose_name="Tipo de Objetos",
                    ),
                ),
                (
                    "variable_shp",
                    models.CharField(max_length=50, verbose_name="Variable SHP"),
                ),
                (
                    "boundary",
                    models.CharField(
                        max_length=50, verbose_name="Limite administrativo OSM"
                    ),
                ),
                (
                    "tag_osm",
                    models.CharField(
                        default="place",
                        max_length=50,
                        verbose_name="Tag de objetos OSM",
                    ),
                ),
                (
                    "variable_osm",
                    models.CharField(
                        max_length=50, verbose_name="Variable a comparar de OSM"
                    ),
                ),
            ],
            options={
                "verbose_name": "SHP Temporal",
                "verbose_name_plural": "SHP Temporales",
            },
        ),
        migrations.CreateModel(
            name="WFSService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("country", models.CharField(max_length=50, verbose_name="Pais")),
                ("url", models.CharField(max_length=200, verbose_name="Url")),
                (
                    "layer",
                    models.CharField(max_length=50, verbose_name="Nombre de Capa"),
                ),
                (
                    "layer_crs",
                    models.CharField(max_length=10, verbose_name="CRS de la capa"),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[("point", "Puntos"), ("line", "Lineas")],
                        max_length=10,
                        verbose_name="Tipo de Objetos",
                    ),
                ),
                (
                    "tag_wfs",
                    models.CharField(
                        default="todo",
                        max_length=50,
                        verbose_name="Tag filtro en la Capa",
                    ),
                ),
                (
                    "variable_wfs",
                    models.CharField(
                        max_length=50, verbose_name="Variable a Comparar WFS*"
                    ),
                ),
                (
                    "tag_osm",
                    models.CharField(
                        default="place",
                        max_length=50,
                        verbose_name="Tag de objetos OSM",
                    ),
                ),
                (
                    "variable_osm",
                    models.CharField(
                        max_length=50, verbose_name="Variable a comparar de OSM"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio WFS",
                "verbose_name_plural": "Servicios WFS",
            },
        ),
    ]
