# Generated by Django 4.1.1 on 2023-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wfsservice",
            name="layer",
            field=models.CharField(max_length=100, verbose_name="Nombre de Capa"),
        ),
        migrations.AlterField(
            model_name="wfsservice",
            name="tag_wfs",
            field=models.CharField(
                default="ninguno", max_length=50, verbose_name="Tag filtro en la Capa"
            ),
        ),
        migrations.AlterField(
            model_name="wfsservice",
            name="url",
            field=models.CharField(max_length=300, verbose_name="Url"),
        ),
    ]
