# Generated by Django 4.1.1 on 2023-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0002_alter_wfsservice_layer_alter_wfsservice_tag_wfs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wfsservice",
            name="bbox_support",
            field=models.BooleanField(default=True),
        ),
    ]
