# Generated by Django 4.1.1 on 2023-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0003_wfsservice_bbox_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wfsservice",
            name="bbox_support",
            field=models.BooleanField(
                default=True, verbose_name="Soporta filtros bbox"
            ),
        ),
    ]
